//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XW {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XW.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Speichern ist in der aktuellen Instanz von &quot;{0}&quot; nicht unterstützt. ähnelt.
        /// </summary>
        public static string ErrCantSaveUsingIdConstructedOneToManyPersister {
            get {
                return ResourceManager.GetString("ErrCantSaveUsingIdConstructedOneToManyPersister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Schreiben in einen Provider vom Typ &quot;{0}&quot; wird nicht unterstützt. ähnelt.
        /// </summary>
        public static string ErrConfigurationProviderWriteNotSupported {
            get {
                return ResourceManager.GetString("ErrConfigurationProviderWriteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Containerschlüssel wurde nicht gefunden. ähnelt.
        /// </summary>
        public static string ErrContainerKeyNotFound {
            get {
                return ResourceManager.GetString("ErrContainerKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im angegebenen Verzeichnis wurden keine Dateien gefunden. ähnelt.
        /// </summary>
        public static string ErrCouldNotFindFilesInPluginDirectory {
            get {
                return ResourceManager.GetString("ErrCouldNotFindFilesInPluginDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im angegebenen Verzeichnis &quot;{0}&quot; konnte keine gültige Pluginassembly gefunden werden. Weitere Informationen befinden sich in der Datei &quot;{1}&quot;. ähnelt.
        /// </summary>
        public static string ErrCouldNotFindValidPluginAssembly {
            get {
                return ResourceManager.GetString("ErrCouldNotFindValidPluginAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Außerhalb eines Updatekontextes kann nicht auf die Datenbankverbindung zugegriffen werden. ähnelt.
        /// </summary>
        public static string ErrDatabaseAccessOutsideMigrationContext {
            get {
                return ResourceManager.GetString("ErrDatabaseAccessOutsideMigrationContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei der Verbindung mit der Datenbank ist ein Fehler aufgetreten. Bitte stellen Sie sicher, dass die Datenbank &quot;{1}&quot; an &quot;{0}&quot; erreichbar und aktuell ist und dass der Benutzer &quot;{2}&quot; berechtigt ist, sich an der Datenbank anzumelden. ähnelt.
        /// </summary>
        public static string ErrDatabaseConnectionError {
            get {
                return ResourceManager.GetString("ErrDatabaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datenbankverbindung muss zugewiesen sein, bevor ein SQL-Kommando ausgeführt werden kann. ähnelt.
        /// </summary>
        public static string ErrDatabaseConnectionNotAssignedBeforeCreatingCommand {
            get {
                return ResourceManager.GetString("ErrDatabaseConnectionNotAssignedBeforeCreatingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zirkuläre Abhängigkeit erkannt. Folgende Elemente konnte nicht erfolgreich verarbeitet werden:
        ///{0} ähnelt.
        /// </summary>
        public static string ErrDetectedCircularReference {
            get {
                return ResourceManager.GetString("ErrDetectedCircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Instance failed to activate. Perhaps there was an error while calling the constructor of the plugin class. ähnelt.
        /// </summary>
        public static string ErrDomainActivationFailed {
            get {
                return ResourceManager.GetString("ErrDomainActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Plugin mit der ID &quot;{0}&quot; ({2}) wurde bereits geladen. Mehrere Instanzen eines Plugins sind zwar zulässig, jedoch kann nicht die vom Plugin angegebene ID verwendet werden. Daher wird eine neue, für die Instanz einmalig generierte ID verwendet. Sollte die Plugininstanz neu installiert werden, so kann nicht garantiert werden, dass danach die gleiche ID gilt. Die generierte ID lautet: &quot;{1}&quot;. ähnelt.
        /// </summary>
        public static string ErrDuplicatePluginIdWarning {
            get {
                return ResourceManager.GetString("ErrDuplicatePluginIdWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate property key ähnelt.
        /// </summary>
        public static string ErrDuplicatePropertyKey {
            get {
                return ResourceManager.GetString("ErrDuplicatePropertyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte keine Instanz des gefundenen Typs &quot;{0}&quot; erzeugt werden. Weitere Informationen befinden sich in der inneren Ausnahme. ähnelt.
        /// </summary>
        public static string ErrFailedToCreateInstanceOfPluginType {
            get {
                return ResourceManager.GetString("ErrFailedToCreateInstanceOfPluginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Bibliothek enthält keine unterstützten Typen. ähnelt.
        /// </summary>
        public static string ErrFailedToLocatePluginType {
            get {
                return ResourceManager.GetString("ErrFailedToLocatePluginType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Lesen der XML-Konfiguration &quot;{0}&quot; ist ein Fehler aufgetreten. Möglicherweise ist die Konfiguration fehlerhaft. {1} ähnelt.
        /// </summary>
        public static string ErrFailedToReadXmlConfiguration {
            get {
                return ResourceManager.GetString("ErrFailedToReadXmlConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die vom System gewählte Auflösung der gemeinsam genutzten Assembly &quot;{0}&quot; ist fehlgeschlagen. Es wird der Fallback-Mechanismus verwendet. Möglicherweise funktioniert das Plugin &quot;{1}&quot; nicht korrekt. Der Fehler lautet: {2} ähnelt.
        /// </summary>
        public static string ErrFailedTouseClientVersionOfSharedAssembly {
            get {
                return ResourceManager.GetString("ErrFailedTouseClientVersionOfSharedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Schreiben der XML-Konfiguration &quot;{0}&quot; ist ein Fehler aufgetreten. {1} ähnelt.
        /// </summary>
        public static string ErrFailedToWriteXmlConfiguration {
            get {
                return ResourceManager.GetString("ErrFailedToWriteXmlConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Authentifizierungsmethode wird nicht unterstützt. ähnelt.
        /// </summary>
        public static string ErrInvalidAuthenticationMethodInConfiguration {
            get {
                return ResourceManager.GetString("ErrInvalidAuthenticationMethodInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiger Wert für &quot;{0}&quot;. ähnelt.
        /// </summary>
        public static string ErrInvalidConfigurationValue {
            get {
                return ResourceManager.GetString("ErrInvalidConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiges Zeichen im Containerschlüssel ähnelt.
        /// </summary>
        public static string ErrInvalidContainerKeyCharacter {
            get {
                return ResourceManager.GetString("ErrInvalidContainerKeyCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Datenbankinstanz ist ungültig. ähnelt.
        /// </summary>
        public static string ErrInvalidDatabaseInstanceInConfiguration {
            get {
                return ResourceManager.GetString("ErrInvalidDatabaseInstanceInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Datenbankname ist ungültig. ähnelt.
        /// </summary>
        public static string ErrInvalidDatabaseNameInConfiguration {
            get {
                return ResourceManager.GetString("ErrInvalidDatabaseNameInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expression is not valid: must be a property of type {0} ähnelt.
        /// </summary>
        public static string ErrInvalidExpressionForExpressionProperty {
            get {
                return ResourceManager.GetString("ErrInvalidExpressionForExpressionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Hostname ist ungültig. ähnelt.
        /// </summary>
        public static string ErrInvalidHostnameInConfiguration {
            get {
                return ResourceManager.GetString("ErrInvalidHostnameInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Port ist ungültig. ähnelt.
        /// </summary>
        public static string ErrInvalidPortInConfiguration {
            get {
                return ResourceManager.GetString("ErrInvalidPortInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Schreiben in die Logdatei &quot;{0}&quot;: {1} ähnelt.
        /// </summary>
        public static string ErrLogfileWriteFailed {
            get {
                return ResourceManager.GetString("ErrLogfileWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Member ist keine Eigenschaft. ähnelt.
        /// </summary>
        public static string ErrMemberIsNotAProperty {
            get {
                return ResourceManager.GetString("ErrMemberIsNotAProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dem Update &quot;{0}&quot; fehlt ein Attribut vom Typ &quot;{1}&quot; ähnelt.
        /// </summary>
        public static string ErrMigrationAttributeMissing {
            get {
                return ResourceManager.GetString("ErrMigrationAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Rollback kann nicht durchgeführt werden. Der Updateschritt &quot;{0}&quot; unterstützt den &quot;{1}&quot;-Aufruf nicht. ähnelt.
        /// </summary>
        public static string ErrMigrationDownNotSupported {
            get {
                return ResourceManager.GetString("ErrMigrationDownNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mismatching buffer sizes. ähnelt.
        /// </summary>
        public static string ErrMismatchingBufferSizes {
            get {
                return ResourceManager.GetString("ErrMismatchingBufferSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist nur ein Anwendungshost pro AppDomain zulässig. ähnelt.
        /// </summary>
        public static string ErrMultipleApplicationHostsInstanced {
            get {
                return ResourceManager.GetString("ErrMultipleApplicationHostsInstanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Im angegebenen Ausdruck kann kein Member von &quot;{0}&quot; gefunden werden: {1} ähnelt.
        /// </summary>
        public static string ErrNotAMemberExpression {
            get {
                return ResourceManager.GetString("ErrNotAMemberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei der Ausführung der Aufgabe &quot;{0}&quot; sind ein oder mehrere Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string ErrorExecutingScheduledAction {
            get {
                return ResourceManager.GetString("ErrorExecutingScheduledAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The {0} must be initialized before. ähnelt.
        /// </summary>
        public static string ErrPluginCollectionNotInitialized {
            get {
                return ResourceManager.GetString("ErrPluginCollectionNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schwerwiegender Fehler innerhalb eines Plugins:
        ///  Id:      	{0}
        ///  Name:   	{1}  
        ///  Version: 	{2}
        ///Weitere Informationen wurden in folgende Datei geschrieben: {3} ähnelt.
        /// </summary>
        public static string ErrPluginFaulted {
            get {
                return ResourceManager.GetString("ErrPluginFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Instanzierung des Typs &quot;{0}&quot; ist nur einmal pro AppDomain erlaubt. ähnelt.
        /// </summary>
        public static string ErrPluginIsImplicitSingleton {
            get {
                return ResourceManager.GetString("ErrPluginIsImplicitSingleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schwerwiegender Fehler bei der Initialisierung eines Moduls. {0} ähnelt.
        /// </summary>
        public static string ErrPluginLoadException {
            get {
                return ResourceManager.GetString("ErrPluginLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Eigenschaften haben ungültige oder fehlende Werte. ähnelt.
        /// </summary>
        public static string ErrPropertiesAreInvalidPlural {
            get {
                return ResourceManager.GetString("ErrPropertiesAreInvalidPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Eigenschaft hat einen ungültigen oder fehlenden Wert. ähnelt.
        /// </summary>
        public static string ErrPropertyIsInvalidSingular {
            get {
                return ResourceManager.GetString("ErrPropertyIsInvalidSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Eigenschaft ist dem Typ &quot;{0}&quot; nicht zuweisbar. ähnelt.
        /// </summary>
        public static string ErrPropertyNotAssignableToRequestedType {
            get {
                return ResourceManager.GetString("ErrPropertyNotAssignableToRequestedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The storage is read-only. ähnelt.
        /// </summary>
        public static string ErrReadonlyStorage {
            get {
                return ResourceManager.GetString("ErrReadonlyStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Attribut &quot;{0}&quot; wurde am Typ &quot;{1}&quot; nicht gefunden. ähnelt.
        /// </summary>
        public static string ErrRequiredAttributeNotFound {
            get {
                return ResourceManager.GetString("ErrRequiredAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine Datenbankabfrage konnte nicht ausgeführt werden. Möglicherweise ist die Datenbank beschädigt oder nicht kompatibel mit der aktuellen Version von LEXolution.Erweiterungsdienst. Folgende Abfrage wurde versucht auszuführen: 
        ///{0}
        ///Sofern weitere Informationen zur Verfügung stehen, werden sie in Folge dieser Ausgabe angegeben.
        ///   ähnelt.
        /// </summary>
        public static string ErrSqlError {
            get {
                return ResourceManager.GetString("ErrSqlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es kann kein untergeordneter Speicher erzeugt werden, da bereits ein Container mit diesem Namen vorhanden ist. ähnelt.
        /// </summary>
        public static string ErrStorageKeyConflictsWithContainer {
            get {
                return ResourceManager.GetString("ErrStorageKeyConflictsWithContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Fehler ist in einem {0} aufgetreten. ähnelt.
        /// </summary>
        public static string ErrSynchronizationContextMessageLoopException {
            get {
                return ResourceManager.GetString("ErrSynchronizationContextMessageLoopException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert darf nicht leer sein. ähnelt.
        /// </summary>
        public static string ErrValueCantBeEmpty {
            get {
                return ResourceManager.GetString("ErrValueCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Wert zwischen {0} und {1} erforderlich. ähnelt.
        /// </summary>
        public static string ErrValueInRangeRequiredValidationError {
            get {
                return ResourceManager.GetString("ErrValueInRangeRequiredValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der angegebene Wert ist kein gültiger numerischer Wert. ähnelt.
        /// </summary>
        public static string ErrValueInvalidDecimalValidationError {
            get {
                return ResourceManager.GetString("ErrValueInvalidDecimalValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie einen Wert ein. ähnelt.
        /// </summary>
        public static string ErrValueRequiredValidationError {
            get {
                return ResourceManager.GetString("ErrValueRequiredValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Bereichselement der Konfiguration entspricht nicht dem erwarteten Element. ähnelt.
        /// </summary>
        public static string ErrXmlConfigurationHasMismatchingContainerNode {
            get {
                return ResourceManager.GetString("ErrXmlConfigurationHasMismatchingContainerNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Root-Element der Konfiguration entspricht nicht dem erwarteten Element. ähnelt.
        /// </summary>
        public static string ErrXmlConfigurationHasMismatchingRootNode {
            get {
                return ResourceManager.GetString("ErrXmlConfigurationHasMismatchingRootNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei der Ausführung der Aufgabe &quot;{0}&quot; ist ein Fehler aufgetreten. ähnelt.
        /// </summary>
        public static string ExceptionExecutingScheduledAction {
            get {
                return ResourceManager.GetString("ExceptionExecutingScheduledAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung wird beendet ähnelt.
        /// </summary>
        public static string LogAppShuttingDown {
            get {
                return ResourceManager.GetString("LogAppShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung wird gestartet ähnelt.
        /// </summary>
        public static string LogAppStarting {
            get {
                return ResourceManager.GetString("LogAppStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: {0} ähnelt.
        /// </summary>
        public static string LogAppVersion {
            get {
                return ResourceManager.GetString("LogAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Verbinden zur Datenbank &quot;{1}&quot; an &quot;{0}&quot; mit der Anmeldung &quot;{2}&quot; ist ein Problem aufgetreten. Neuer Versuch in {4} Sekunden ({5} Versuche verbleibend)... ähnelt.
        /// </summary>
        public static string LogDatabaseConnectionErrorWithRetryPending {
            get {
                return ResourceManager.GetString("LogDatabaseConnectionErrorWithRetryPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Datenbank existiert nicht. Sie wird automatisch angelegt. Bitte stellen Sie sicher, dass die Datenbank nach dem Update korrekt konfiguriert wird. ähnelt.
        /// </summary>
        public static string LogDatabaseCreateWarning {
            get {
                return ResourceManager.GetString("LogDatabaseCreateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folgende Informationen stehen zum Fehler zur Verfügung:
        ///{0}
        ///{1} ähnelt.
        /// </summary>
        public static string LogFaultMessageMoreInformation {
            get {
                return ResourceManager.GetString("LogFaultMessageMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Protokolltabelle gefunden. Es wird von einer Erstinstallation ausgegangen. ähnelt.
        /// </summary>
        public static string LogIntialDatabaseMigrationNotice {
            get {
                return ResourceManager.GetString("LogIntialDatabaseMigrationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Update wurde aufgrund von Fehlern abgebrochen. ähnelt.
        /// </summary>
        public static string LogMigrationCanceled {
            get {
                return ResourceManager.GetString("LogMigrationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start der Ausführung des Updates &quot;{0}&quot; auf Version {1} ähnelt.
        /// </summary>
        public static string LogMigrationStepIntro {
            get {
                return ResourceManager.GetString("LogMigrationStepIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin wurde erfolgreich initialisiert:
        ///  Id:             	{0}
        ///  Name:     	{1}
        ///  Version: 	{2} ähnelt.
        /// </summary>
        public static string LogPluginInitializationMessage {
            get {
                return ResourceManager.GetString("LogPluginInitializationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In registrierten RTLEs aufgeführte Ausnahmen: ähnelt.
        /// </summary>
        public static string LogPluginLoadingFaultExceptionsBanner {
            get {
                return ResourceManager.GetString("LogPluginLoadingFaultExceptionsBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laden von {0}: {1} ähnelt.
        /// </summary>
        public static string LogPluginLoadingFaultRtleBanner {
            get {
                return ResourceManager.GetString("LogPluginLoadingFaultRtleBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In registrierten RTLEs aufgeführte Typen: ähnelt.
        /// </summary>
        public static string LogPluginLoadingFaultTypesBanner {
            get {
                return ResourceManager.GetString("LogPluginLoadingFaultTypesBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SQL-Fehler bei Zeile {0}: {1} - das Update &quot;{2}&quot; auf Version {3} ist fehlgeschlagen. ähnelt.
        /// </summary>
        public static string LogSqlErrorDuringMigration {
            get {
                return ResourceManager.GetString("LogSqlErrorDuringMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginne Aufgabe &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string LogStartingAction {
            get {
                return ResourceManager.GetString("LogStartingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beende Aufgabe &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string LogStoppingAction {
            get {
                return ResourceManager.GetString("LogStoppingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Zielversion ist größer als die aktuelle Datenbankversion. Es wurden keine Aktionen ausgeführt. ähnelt.
        /// </summary>
        public static string LogTargetDatabaseVersionGreaterThanCurrent {
            get {
                return ResourceManager.GetString("LogTargetDatabaseVersionGreaterThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Zielversion ist kleiner als die aktuelle Datenbankversion. Es werden keine Aktionen ausgeführt. ähnelt.
        /// </summary>
        public static string LogTargetDatabaseVersionLowerThanCurrent {
            get {
                return ResourceManager.GetString("LogTargetDatabaseVersionLowerThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gemeinsame Assembly &quot;{0}&quot; wird durch die Pluginumgebung bereitgestellt. ähnelt.
        /// </summary>
        public static string LogUsingClientVersionOfSharedAssembly {
            get {
                return ResourceManager.GetString("LogUsingClientVersionOfSharedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gemeinsame Assembly &quot;{0}&quot; wird durch die Hostumgebung bereitgestellt. ähnelt.
        /// </summary>
        public static string LogUsingHostVersionOfSharedAssembly {
            get {
                return ResourceManager.GetString("LogUsingHostVersionOfSharedAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde keine Instanz vom Typ &quot;{0}&quot; registriert. ähnelt.
        /// </summary>
        public static string NoInstanceOfTypeRegisteredInContainer {
            get {
                return ResourceManager.GetString("NoInstanceOfTypeRegisteredInContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurden keine Suchergebnisse gefunden. ähnelt.
        /// </summary>
        public static string UiNoSearchResults {
            get {
                return ResourceManager.GetString("UiNoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drücken Sie eine beliebige Taste, um fortzufahren . . . ähnelt.
        /// </summary>
        public static string UiPressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("UiPressAnyKeyToContinue", resourceCulture);
            }
        }
    }
}
